### ISSUE TITLE
UserWarning: This figure includes Axes that are not compatible with tight_layout

### ISSUE THREAD

**Issue by lincolnfrias** [ligyxy/PyWaffle#1]
First of all, incredibly awesome and fun package. Thanks a lot!

I'm getting this warning in all the plots:

> UserWarning: This figure includes Axes that are not compatible with tight_layout, so results might be incorrect.  warnings.warn("This figure includes Axes that are not compatible ").

It seems a false positive in this context, right?

**Comment by ligyxy** [comment]
I notice this issue too. The reason of it is that tight_layout is turned on as it says. So you can do `fig.set_tight_layout(False)` to cancel the tight layout and this warning would be gone.

However, tight layout is pretty necessary in the multiple plots case, to give subplots' title enough space. will probably make a better default value for the tight_layout setting.

**Comment by ProsperousHeart** [comment]
Why was this closed? This doesn't resolve the issue, since it should be compatible or documentation should be more clear.

**Comment by ligyxy** [comment]
@ProsperousHeart Could you show me how to reproduce this warning? With matplotlib 3.0.2, I don't see this warning anymore.

**Comment by BAFurtado** [comment]
Hi,
Awesome. Yes, I get the warning with matplotlib 3.03

**Comment by Lxiangyue** [comment]
That's right. Different versions result in different results. When I use matplotlib 2.0.1, an error reported. While using matplotlib 3.0.1, everything goes right.
