### ISSUE TITLE
block present when value is 0

### ISSUE THREAD

**Issue by glaubius** [ligyxy/PyWaffle#11]
Hi! Thanks for creating PyWaffle and the useful examples.

I started using it today and everything is great, except that sometimes I have a value of 0 for some items. But when the waffle chart is generated, a block is still present for the category with a value of 0. 
<img width="849" alt="Screen Shot 2019-08-30 at 4 53 12 PM" src="https://user-images.githubusercontent.com/5349064/64050860-46a75a00-cb47-11e9-805f-5827373dd322.png">

Could you look into making it so that there is no block for a label if the value is 0?

**Comment by ligyxy** [comment]
Thanks for pointing out! This is fixed in 0.2.2. Please update the package.
