### ISSUE TITLE
Font file not found when using FontAwesome icons

### ISSUE THREAD

**Issue by mostlyoxygen** [ligyxy/PyWaffle#4]
When creating a chart with icons a `FileNotFoundError` is thrown, whilst looking for the file `font/FontAwesome.otf`.  This seems to be because it's trying to find the file relative to the location of the calling script, rather than in the `font` package created during installation.

A simple fix for this would be to modify `waffle.py` to import the `font` package and use its `__path__` value to construct the path to the FontAwesome file:

```python
import font
import os
FONTAWESOME_FILE = os.path.join(font.__path__[0], 'FontAwesome.otf')
```

If you're happy with this fix I can make a pull request.

**Comment by ligyxy** [comment]
That's a good one. Fixed.

Thank you!

**Comment by mostlyoxygen** [comment]
Thanks for fixing it so quickly.
